### ISSUE TITLE
Add a gradient to the "Color Picker" heading

### ISSUE THREAD

**Issue by ArkaPrabhaChowdhury** [SscSPs/color#57]
This would showcase the variety of colours available in the react app. Please assign this task to me.

**Comment by Drex72** [comment]
Hi, I'm interested in this issue. Can i be assigned to it?

**Comment by SscSPs** [comment]
@ArkaPrabhaChowdhury sounds good, the gradient shouldn't be too pronounced and should have good enough contrast ratio with the background, so it's readable enough

@Drex72 since @ArkaPrabhaChowdhury created this, probably they wanna work on this, so let them reply with their response of they wanna work on this or if you can work on it!

**Comment by ArkaPrabhaChowdhury** [comment]
Yes, the gradient would be light but beautiful and readable. I would love to work on this.

**Comment by SscSPs** [comment]
Awesome! I'll assign it to you :)

**Comment by ArkaPrabhaChowdhury** [comment]
Could you please add the hacktoberfest label?

**Comment by SscSPs** [comment]
It's not needed, the repo itself has it

**Comment by SscSPs** [comment]
I added to others only to let new people know that it's worth looking at if they are here from hacktoberfest

**Comment by kushaljgec2025** [comment]
please assign me this work .
